version: 2

sources:
  - name: raw
    schema: main
    tables:
      - name: fact_articles
      - name: dim_entity
      - name: bridge_article_entity
      - name: dim_date
      - name: dim_source
